import { CurriculumDay } from '../types/curriculum';

export const MONTH_3_DAYS: CurriculumDay[] = [
  {
    day: 61,
    month: 3,
    week: 9,
    domainId: 'evaluation',
    title: 'The Science of Hallucinations: Taxonomy & Causes',
    shortSummary: 'Understand the underlying causes of LLM hallucinations: parametric memory vs grounding, relational drift, and confidence calibration.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Deconstruct the taxonomy of AI hallucinations (Factual, Relational, Source attribution, Reasoning gap)',
      'Explain why LLMs hallucinate with high linguistic confidence',
      'Understand how temperature and prompt grounding affect hallucination rates'
    ],
    conceptGuide: 'Output Evaluation and Validation represents 21% of the CCAO-F exam. Hallucinations occur because models predict statistically probable next tokens rather than retrieving from an internal truth database. A model can produce completely false facts in fluent, authoritative prose.',
    handsOnExercise: {
      taskName: 'Hallucination Generation & Detection Lab',
      instructions: 'Prompt Claude on an obscure or fictitious topic without providing source context. Observe where plausible-sounding fabrications emerge.',
      promptTemplate: 'Summarize the primary conclusions of the 2019 Stanford study by Dr. Marcus Sterling on high-altitude quantum tunneling.',
      expectedOutcome: 'Observe if Claude flags that Dr. Marcus Sterling / the study does not exist, or hallucinates believable details.'
    },
    tasks: [
      { id: 'd61-t1', text: 'Study research papers on hallucination taxonomy in large language models', durationMinutes: 25 },
      { id: 'd61-t2', text: 'Execute hallucination probe prompts and analyze response tone', durationMinutes: 25 },
      { id: 'd61-t3', text: 'Document the 4 hallucination categories in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'Claude 3.5 Sonnet has remarkably low hallucination rates when grounded, but ungrounded prompts on obscure topics can still produce errors.',
    examTrapWarning: 'High confidence and eloquent prose do NOT equal factual accuracy. The exam heavily tests your ability to distrust unverified fluency.'
  },
  {
    day: 62,
    month: 3,
    week: 9,
    domainId: 'evaluation',
    title: 'Spotting Fabricated Citations, URLs & False Statistics',
    shortSummary: 'Detect subtle synthetic errors: non-existent academic papers, hallucinated web URLs, manipulated DOI numbers, and fabricated statistics.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Identify typical hallmarks of hallucinated citations (real journal names with fictional author combinations)',
      'Spot fake URLs (syntactically valid URLs that lead to 404 dead ends)',
      'Verify statistics against primary source documents'
    ],
    conceptGuide: 'When asked to provide sources without internet access or reference text, models often synthesize convincing citations with real journal titles but fictional authors or dates.',
    handsOnExercise: {
      taskName: 'Citation Forensic Audit',
      instructions: 'Review 5 citations generated by an LLM. Use search or academic directories to verify author, publication year, and volume numbers.',
      expectedOutcome: 'Identify the 2 fabricated citations mixed with real publications.'
    },
    tasks: [
      { id: 'd62-t1', text: 'Learn forensic verification methods for AI-generated citations and URLs', durationMinutes: 20 },
      { id: 'd62-t2', text: 'Audit 5 generated research summaries for citation integrity', durationMinutes: 30 },
      { id: 'd62-t3', text: 'Establish enterprise citation verification checklist', durationMinutes: 10 }
    ],
    mentorTip: 'Never copy-paste URLs or academic citations from an LLM into an executive report without clicking and verifying them first.',
    examTrapWarning: 'Exam questions often show an excerpt containing 3 real facts and 1 fake citation. Your job is to identify the unverified claim.'
  },
  {
    day: 63,
    month: 3,
    week: 9,
    domainId: 'evaluation',
    title: 'The Rigorous Fact-Checking Framework & Verification Rubric',
    shortSummary: 'Deploy a repeatable 4-step fact-checking methodology: Claim Isolation, Primary Reconciliation, Boundary Verification, and Confidence Scoring.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Master the 4-step Verification Rubric used by enterprise validation teams',
      'Deconstruct complex paragraphs into atomic, testable claims',
      'Reconcile atomic claims against authoritative ground-truth records'
    ],
    conceptGuide: 'To fact-check effectively, you must isolate individual factual assertions (dates, names, metrics, causality) and check each against a trusted primary source.',
    handsOnExercise: {
      taskName: 'Atomic Claim Extraction & Verification',
      instructions: 'Take a 3-paragraph summary of a quarterly financial release. Break it into 8 atomic claims and cross-reference against the raw financial table.',
      expectedOutcome: 'Spot subtle discrepancies in rounding and attribution.'
    },
    tasks: [
      { id: 'd63-t1', text: 'Study the Atomic Claim Verification methodology', durationMinutes: 25 },
      { id: 'd63-t2', text: 'Perform atomic claim audit on a business earnings summary', durationMinutes: 25 },
      { id: 'd63-t3', text: 'Document the 4-step verification rubric in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'Pay special attention to numerical claims that involve math performed across two separate sections of the source.',
    examTrapWarning: 'Do not use another AI prompt to verify the first AI without providing the authoritative source text.'
  },
  {
    day: 64,
    month: 3,
    week: 9,
    domainId: 'evaluation',
    title: 'Evaluating Logical Consistency & Reasoning Traces',
    shortSummary: 'Audit Claude multi-step reasoning: identify non-sequiturs, circular reasoning, contradictory conclusions, and false causal links.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Trace logical flow in complex multi-step deductive arguments',
      'Identify instances where the conclusion contradicts premises stated earlier in the response',
      'Spot correlation-vs-causation conflation in AI analysis'
    ],
    conceptGuide: 'Sometimes Claude states completely accurate facts in Paragraph 1 and Paragraph 2, but draws a logically invalid conclusion in Paragraph 3. Evaluating reasoning requires checking the inferential link.',
    handsOnExercise: {
      taskName: 'Reasoning Trace Audit Drill',
      instructions: 'Inspect a complex business case recommendation generated by Claude. Verify whether the recommended action mathematically follows from the premises.',
      expectedOutcome: 'Spot an unjustified assumption connecting market growth to profit margin.'
    },
    tasks: [
      { id: 'd64-t1', text: 'Study common logical fallacies found in generative AI synthesis', durationMinutes: 25 },
      { id: 'd64-t2', text: 'Evaluate 3 reasoning traces from complex strategy prompts', durationMinutes: 25 },
      { id: 'd64-t3', text: 'Document logical consistency audit checklist in study log', durationMinutes: 10 }
    ],
    mentorTip: 'Check the transition words: "Therefore", "Consequently", "As a result". Ensure the causal link is genuinely substantiated.',
    examTrapWarning: 'Exam questions often test whether you can spot conclusions that sound plausible but do not logically follow from the input text.'
  },
  {
    day: 65,
    month: 3,
    week: 9,
    domainId: 'evaluation',
    title: 'Spotting Omissions, Cherry-Picking & Unbalanced Synthesis',
    shortSummary: 'Evaluate completeness: detect critical omitted risks, selective data presentation, and failure to address edge-case constraints.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Evaluate whether Claude followed ALL instructions or omitted uncomfortable edge cases',
      'Identify "cherry-picking" where only supportive data is cited while contrary data is ignored',
      'Audit document syntheses for structural omissions'
    ],
    conceptGuide: 'An output can be 100% factually accurate yet dangerously misleading if it omits a critical negative consequence or regulatory caveat.',
    handsOnExercise: {
      taskName: 'Omission Detection Audit',
      instructions: 'Upload a 10-page contract containing standard clauses and one critical indemnification exception. Ask for a summary and check if the exception was omitted.',
      expectedOutcome: 'Identify if Claude summarized the common parts while glossing over the crucial exception clause.'
    },
    tasks: [
      { id: 'd65-t1', text: 'Study omission risks and coverage completeness in LLM summarization', durationMinutes: 20 },
      { id: 'd65-t2', text: 'Conduct omission audit on contract and policy summaries', durationMinutes: 30 },
      { id: 'd65-t3', text: 'Formulate prompt patterns that force comprehensive exception reporting', durationMinutes: 10 }
    ],
    mentorTip: 'Always prompt Claude: "Explicitly highlight any exceptions, limitations, edge cases, and contrary data found in the text."',
    examTrapWarning: 'In the exam, a summary that leaves out key business constraints is considered an invalid or failing output.'
  },
  {
    day: 66,
    month: 3,
    week: 9,
    domainId: 'evaluation',
    title: 'Quantitative Validation: Verifying Math & Financial Totals',
    shortSummary: 'Audit numerical calculations, spreadsheet formulas, percentages, and financial totals produced by Claude.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Understand why LLMs struggle with large multi-digit multiplication and complex financial compounding',
      'Verify row/column totals and percentage distributions in AI-generated tables',
      'Recommend code execution / spreadsheet tools for high-precision math'
    ],
    conceptGuide: 'LLMs are language prediction engines, not calculators. While Claude 3.5 Sonnet is remarkably adept at math when using chain-of-thought, all financial calculations must be verified with code or a calculator.',
    handsOnExercise: {
      taskName: 'Financial Table Reconciliation Drill',
      instructions: 'Review a Claude-generated table with 10 financial line items, subtotals, and year-over-year percentage variances. Audit every cell with a spreadsheet.',
      expectedOutcome: 'Locate subtle arithmetic errors in compound growth calculation.'
    },
    tasks: [
      { id: 'd66-t1', text: 'Review arithmetic limitations and token-based numerical prediction mechanics', durationMinutes: 20 },
      { id: 'd66-t2', text: 'Audit 3 generated financial balance sheets for arithmetic consistency', durationMinutes: 30 },
      { id: 'd66-t3', text: 'Document math verification policies for enterprise financial reports', durationMinutes: 10 }
    ],
    mentorTip: 'For mission-critical math, have Claude write and execute Python code in Artifacts/Analysis tool rather than doing mental math.',
    examTrapWarning: 'Never accept AI-generated financial totals in an exam scenario without recommending independent calculation verification.'
  },
  {
    day: 67,
    month: 3,
    week: 9,
    domainId: 'evaluation',
    title: 'Week 9 Milestone: Output Validation & Error Spotting Lab',
    shortSummary: 'Pass the high-intensity Output Validation Lab (Domain 1, 21% weight): spot 10 subtle errors in simulated enterprise outputs.',
    timeAllocation: { conceptMinutes: 15, handsOnMinutes: 30, reviewMinutes: 15 },
    learningObjectives: [
      'Consolidate all Week 9 Output Evaluation skills (Hallucinations, Citations, Logic, Omissions, Math)',
      'Score 90%+ on Domain 1 forensic scenario questions',
      'Earn the Validation & Risk Auditor milestone badge'
    ],
    conceptGuide: 'Domain 1 is 21% of your total exam score. Excelling in Output Evaluation provides the highest single-domain point yield on the CCAO-F exam.',
    handsOnExercise: {
      taskName: 'Forensic Validation Exam Simulation',
      instructions: 'Review 5 realistic business output excerpts. Identify the precise factual, logical, or mathematical flaw in each.',
      expectedOutcome: '100% detection rate on seeded errors.'
    },
    tasks: [
      { id: 'd67-t1', text: 'Review Week 9 validation rubrics and error categories', durationMinutes: 15 },
      { id: 'd67-t2', text: 'Complete Week 9 milestone exam drill in simulator', durationMinutes: 30 },
      { id: 'd67-t3', text: 'Analyze rationales and solidify error spotting intuition', durationMinutes: 15 }
    ],
    mentorTip: 'Congratulations on mastering Domain 1! You now possess the critical discernment that defines a true Claude Certified Associate.',
    examTrapWarning: 'Read every multiple-choice option carefully. The flaw is often disguised within otherwise eloquent prose.',
    isMilestone: true,
    milestoneTitle: 'Output Validation Specialist (Week 9 Cleared)',
    milestoneReward: 'Badge: Validation Specialist Medal Unlocked'
  },
  {
    day: 68,
    month: 3,
    week: 10,
    domainId: 'troubleshooting',
    title: 'Diagnosing Root Causes of Output Failures',
    shortSummary: 'Apply the 5-point root-cause matrix: Ambiguity, Overloaded Context, Conflicting Constraints, Insufficient Examples, or Capability Limit.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Map failed outputs to their underlying root cause',
      'Distinguish between model capability limits vs prompt engineering defects',
      'Execute systematic prompt fixes based on identified root causes'
    ],
    conceptGuide: 'Troubleshooting and Optimization (10% of exam) requires methodical problem-solving. When an output fails, jumping to random rewrites wastes time. Use the diagnostic matrix to target the defect.',
    handsOnExercise: {
      taskName: 'Root Cause Classification Drill',
      instructions: 'Review 5 failed prompt-output pairs. Categorize each into: Ambiguous Instruction, Conflicting Rules, Context Dilution, Missing Examples, or Capability Limit.',
      expectedOutcome: 'Accurate root cause identification for all 5 pairs.'
    },
    tasks: [
      { id: 'd68-t1', text: 'Study the 5-point root-cause diagnostic matrix', durationMinutes: 25 },
      { id: 'd68-t2', text: 'Diagnose and fix 5 broken enterprise prompts', durationMinutes: 25 },
      { id: 'd68-t3', text: 'Document troubleshooting flow in personal study notes', durationMinutes: 10 }
    ],
    mentorTip: '90% of AI output failures stem from ambiguous instructions or conflicting constraints in the prompt, not model defects.',
    examTrapWarning: 'Don\'t switch models until you have verified that the prompt itself is clear, well-structured, and unambiguous.'
  },
  {
    day: 69,
    month: 3,
    week: 10,
    domainId: 'troubleshooting',
    title: 'Troubleshooting "Lazy" Responses & Truncated Outputs',
    shortSummary: 'Fix incomplete generations: eliminate placeholder code comments ("// rest of code here"), enforce full document completion, and manage token limits.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Understand why models generate lazy placeholders like "// continue implementation..."',
      'Enforce complete, exhaustive generations without truncated sections',
      'Manage maximum output token limits (max_tokens parameter)'
    ],
    conceptGuide: 'When asked to refactor long code or rewrite an entire 10-page document, models may produce truncated placeholders to conserve tokens. Explicitly demanding completeness eliminates lazy generation.',
    handsOnExercise: {
      taskName: 'Anti-Laziness Prompt Optimization',
      instructions: 'Refactor a prompt to force Claude to write out an entire 80-line configuration without placeholders or omissions.',
      promptTemplate: 'Write the complete, full configuration file. Do NOT use comments like "// same as before" or "// add remaining items here". Include every single line.',
      expectedOutcome: '100% complete generation with zero placeholder comments.'
    },
    tasks: [
      { id: 'd69-t1', text: 'Study token generation dynamics and laziness triggers in LLMs', durationMinutes: 20 },
      { id: 'd69-t2', text: 'Test anti-laziness prompt instructions on large code/text rewrites', durationMinutes: 30 },
      { id: 'd69-t3', text: 'Document phrases that successfully enforce full completion', durationMinutes: 10 }
    ],
    mentorTip: 'Use explicit phrases: "Output the full, unabridged file from start to finish. Do not truncate or use placeholders under any circumstances."',
    examTrapWarning: 'If an output cuts off abruptly mid-sentence, it hit the max_tokens ceiling, not a laziness issue. Increase max_tokens or chain the prompt.'
  },
  {
    day: 70,
    month: 3,
    week: 10,
    domainId: 'troubleshooting',
    title: 'Addressing Instruction Drift in Extended Conversations',
    shortSummary: 'Recognize when conversation history degrades quality, prune conversation state, and determine when to fork or reset chats.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Detect the onset of instruction drift in long, multi-turn chat sessions',
      'Apply conversation branching and thread reset techniques',
      'Transfer context cleanly into fresh conversation threads'
    ],
    conceptGuide: 'In a 30-turn chat, early formatting rules and system boundaries lose attention weight. Experienced Claude users maintain high performance by starting fresh threads with synthesized summaries.',
    handsOnExercise: {
      taskName: 'Context Synthesis & Clean Hand-off Lab',
      instructions: 'Take a long 15-turn project chat. Prompt Claude to generate a concise State Summary, then start a brand-new chat initialized with that summary.',
      expectedOutcome: 'Restored lightning-fast adherence to formatting rules in the fresh thread.'
    },
    tasks: [
      { id: 'd70-t1', text: 'Analyze attention degradation over 20+ turn conversation histories', durationMinutes: 25 },
      { id: 'd70-t2', text: 'Practice thread synthesis and clean hand-off workflow', durationMinutes: 25 },
      { id: 'd70-t3', text: 'Document rules for when to abandon a chat thread', durationMinutes: 10 }
    ],
    mentorTip: 'When Claude starts repeatedly ignoring a rule you gave 10 turns ago, don\'t argue with it in that thread. Reset and state the rule in Turn 1.',
    examTrapWarning: 'Continuing an increasingly erratic chat thread is an exam anti-pattern. Starting a new focused session is the right move.'
  },
  {
    day: 71,
    month: 3,
    week: 10,
    domainId: 'troubleshooting',
    title: 'Fixing Formatting Breakdowns & Schema Violations',
    shortSummary: 'Eliminate malformed JSON, unclosed quotes, markdown wrappers, and invalid table syntax in production workflows.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Diagnose syntax errors in generated JSON, CSV, and markdown tables',
      'Use few-shot syntax anchors to enforce strict closing brackets',
      'Implement prompt validation loops for automated error recovery'
    ],
    conceptGuide: 'When automated parsers crash on Claude output, the issue is usually an unescaped double quote inside a string or markdown code fences enclosing the JSON payload. Strict constraints prevent this.',
    handsOnExercise: {
      taskName: 'Strict JSON Schema Enforcement Lab',
      instructions: 'Prompt Claude to extract complex nested text containing quotes and apostrophes into 100% valid JSON without markdown ticks.',
      promptTemplate: 'Return raw JSON only without markdown code fences (no ```json). Ensure all inner quotation marks are properly escaped.',
      expectedOutcome: 'Directly parseable JSON payload.'
    },
    tasks: [
      { id: 'd71-t1', text: 'Study JSON formatting failure points in LLM pipelines', durationMinutes: 20 },
      { id: 'd71-t2', text: 'Test nested entity extraction with quotes and special characters', durationMinutes: 30 },
      { id: 'd71-t3', text: 'Document bulletproof schema enforcement patterns in notes', durationMinutes: 10 }
    ],
    mentorTip: 'Providing a 1-shot example of the exact expected JSON schema reduces syntax errors to near zero.',
    examTrapWarning: 'Do not tell Claude to output JSON while also asking it to explain its reasoning in the same turn without using separate tags.'
  },
  {
    day: 72,
    month: 3,
    week: 10,
    domainId: 'troubleshooting',
    title: 'Resolving False-Positive Model Refusals',
    shortSummary: 'Differentiate legitimate safety refusals from overly conservative false-positives, and learn neutral reframing techniques.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Distinguish genuine AUP violations from benign enterprise queries',
      'Identify trigger phrases that mistakenly trigger safety heuristics (e.g. "attack", "exploit", "kill")',
      'Neutralize terminology and provide explicit benign business context'
    ],
    conceptGuide: 'Sometimes Claude refuses a legitimate query like "How do competitors attack our market share?" because of the word "attack". Reframing with neutral business vocabulary ("How do competitors compete against our market position?") eliminates false refusals.',
    handsOnExercise: {
      taskName: 'Refusal Refactoring Drill',
      instructions: 'Take 3 legitimate business queries that could trigger conservative refusals and rewrite them using neutral, non-violent business terminology.',
      expectedOutcome: 'High-quality responses without safety refusals.'
    },
    tasks: [
      { id: 'd72-t1', text: 'Study safety alignment heuristics and common refusal triggers', durationMinutes: 25 },
      { id: 'd72-t2', text: 'Practice neutral reframing on 3 sensitive business prompts', durationMinutes: 25 },
      { id: 'd72-t3', text: 'Document acceptable reframing strategies in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'State the legitimate enterprise purpose, your professional role, and the analytical context up front.',
    examTrapWarning: 'If a request genuinely violates Anthropic Acceptable Use Policy, reframing to trick the model is unethical and violates exam principles.'
  },
  {
    day: 73,
    month: 3,
    week: 10,
    domainId: 'troubleshooting',
    title: 'Token Economics, Prompt Trimming & Latency Tuning',
    shortSummary: 'Optimize performance: trim verbose prompts, reduce redundant context, compress instructions, and lower latency by 50%.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Identify prompt bloat and unnecessary filler in enterprise templates',
      'Compress a 1,000-word prompt into 300 words without losing semantic fidelity',
      'Measure latency improvements from prompt compression'
    ],
    conceptGuide: 'Longer prompts take longer to process and cost more money. Trimming repetitive instructions, removing conversational preambles, and using concise bullet directives drastically reduces latency.',
    handsOnExercise: {
      taskName: 'Prompt Compression Challenge',
      instructions: 'Take a verbose 800-token prompt. Edit it down to under 250 tokens while maintaining identical output quality and adherence.',
      expectedOutcome: 'Same high-quality output generated at 2x the speed.'
    },
    tasks: [
      { id: 'd73-t1', text: 'Study token optimization and latency reduction techniques', durationMinutes: 25 },
      { id: 'd73-t2', text: 'Compress 2 corporate prompt templates by at least 50%', durationMinutes: 25 },
      { id: 'd73-t3', text: 'Document token compression rules in study log', durationMinutes: 10 }
    ],
    mentorTip: 'Every token in your prompt costs time and attention. If a word doesn\'t add precision or constraint, cut it.',
    examTrapWarning: 'Do not compress to the point of ambiguity. Clarity always trumps extreme brevity.'
  },
  {
    day: 74,
    month: 3,
    week: 10,
    domainId: 'troubleshooting',
    title: 'Week 10 Milestone: Troubleshooting & Optimization Mastery',
    shortSummary: 'Pass the Troubleshooting & Optimization assessment (Domain 7, 10% weight) and unlock the Diagnostic Specialist badge.',
    timeAllocation: { conceptMinutes: 15, handsOnMinutes: 30, reviewMinutes: 15 },
    learningObjectives: [
      'Consolidate Week 10 troubleshooting and debugging competencies',
      'Score 90%+ on Domain 7 diagnostic scenario questions',
      'Unlock the Diagnostic Specialist milestone badge'
    ],
    conceptGuide: 'You have now completed focused study on ALL 7 DOMAINS of the CCAO-F syllabus! The remaining weeks will be dedicated to high-impact scenario drills and full-length timed mock exams.',
    handsOnExercise: {
      taskName: 'Domain 7 Diagnostic Exam Drill',
      instructions: 'Complete 10 scenario questions diagnosing prompt failures, laziness, instruction drift, schema errors, and token optimization.',
      expectedOutcome: 'Mastery of all Domain 7 exam concepts.'
    },
    tasks: [
      { id: 'd74-t1', text: 'Review Week 10 diagnostic matrices and cheat sheets', durationMinutes: 15 },
      { id: 'd74-t2', text: 'Complete Week 10 milestone exam drill in simulator', durationMinutes: 30 },
      { id: 'd74-t3', text: 'Review explanations for any missed questions', durationMinutes: 15 }
    ],
    mentorTip: 'All 7 syllabus domains are now complete! You have built a comprehensive knowledge base across every tested topic.',
    examTrapWarning: 'Do not let your guard down. Weeks 11 and 12 are where you build the test-taking stamina needed for the 120-minute real exam.',
    isMilestone: true,
    milestoneTitle: 'Diagnostic Specialist (Week 10 Cleared)',
    milestoneReward: 'Badge: Diagnostic Specialist Medal Unlocked'
  },
  {
    day: 75,
    month: 3,
    week: 11,
    domainId: 'workflow',
    title: 'Scenario Drill 1: The High-Stakes Business Consultant',
    shortSummary: 'Master complex multi-domain scenario questions: Model selection, workflow chaining, and executive reporting under tight deadlines.',
    timeAllocation: { conceptMinutes: 20, handsOnMinutes: 30, reviewMinutes: 10 },
    learningObjectives: [
      'Dissect complex multi-paragraph scenario questions found on the CCAO-F exam',
      'Identify the real decision criteria hidden inside distracting background details',
      'Select the optimal model and workflow pattern for high-stakes consulting'
    ],
    conceptGuide: 'The CCAO-F exam uses lengthy scenario questions describing a company\'s dilemma. Learn to identify the core constraint (Speed? Cost? Accuracy? Privacy?) and eliminate options that violate it.',
    handsOnExercise: {
      taskName: 'Consulting Scenario Walkthrough',
      instructions: 'Analyze an exam scenario describing a strategy firm evaluating 50 acquisition targets. Determine the model, prompt architecture, and review gates.',
      expectedOutcome: 'Selection of Sonnet with sequential prompt chaining and mandatory human financial review.'
    },
    tasks: [
      { id: 'd75-t1', text: 'Study scenario decomposition strategies for 60-question exams', durationMinutes: 20 },
      { id: 'd75-t2', text: 'Complete 4 multi-paragraph business consulting scenario questions', durationMinutes: 30 },
      { id: 'd75-t3', text: 'Document key decision filters in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'Identify the "non-negotiable constraint" first. If the scenario says "Budget is extremely tight", eliminate Opus immediately.',
    examTrapWarning: 'Do not get distracted by the industry flavor of the scenario. The underlying AI decision principle is what matters.'
  },
  {
    day: 76,
    month: 3,
    week: 11,
    domainId: 'governance',
    title: 'Scenario Drill 2: Healthcare & Financial Compliance',
    shortSummary: 'Navigate regulated industry scenarios: HIPAA, GLBA, PII masking, audit trails, and strict human review mandates.',
    timeAllocation: { conceptMinutes: 20, handsOnMinutes: 30, reviewMinutes: 10 },
    learningObjectives: [
      'Solve scenario questions set in healthcare, banking, and government environments',
      'Identify non-compliant proposals that bypass PII redaction or human sign-off',
      'Select legally sound architectures for regulated enterprises'
    ],
    conceptGuide: 'Regulated industry questions test whether you understand that AI can assist analysis but cannot autonomously transmit patient data or issue credit denials without human review.',
    handsOnExercise: {
      taskName: 'Regulated Scenario Defense',
      instructions: 'Review 3 healthcare and financial AI integration proposals. Identify the single regulatory flaw in each and propose the compliant fix.',
      expectedOutcome: 'Confident application of compliance guardrails.'
    },
    tasks: [
      { id: 'd76-t1', text: 'Review healthcare (HIPAA) and financial regulatory AI standards', durationMinutes: 20 },
      { id: 'd76-t2', text: 'Complete 4 regulated industry scenario questions in simulator', durationMinutes: 30 },
      { id: 'd76-t3', text: 'Document regulated workflow patterns in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'Whenever a scenario involves patient records or credit scores, any option lacking human oversight or PII masking is automatically wrong.',
    examTrapWarning: 'Anthropic commercial terms do NOT make an enterprise automatically HIPAA compliant without a signed BAA and pre-redaction protocols.'
  },
  {
    day: 77,
    month: 3,
    week: 11,
    domainId: 'knowledge',
    title: 'Scenario Drill 3: Marketing & Content Operations',
    shortSummary: 'Solve content pipeline scenarios: Claude Projects for brand voice, Artifacts for creative assets, and multi-channel campaign automation.',
    timeAllocation: { conceptMinutes: 20, handsOnMinutes: 30, reviewMinutes: 10 },
    learningObjectives: [
      'Configure Claude Projects for global brand voice consistency',
      'Deploy Artifacts for marketing dashboards, campaign trackers, and creative mockups',
      'Balance brand creativity with hallucination risk in marketing claims'
    ],
    conceptGuide: 'Marketing teams leverage Claude for rapid campaign ideation and copy variants. The key exam consideration is ensuring brand guidelines in Project Instructions prevent tone drift.',
    handsOnExercise: {
      taskName: 'Marketing Pipeline Optimization Lab',
      instructions: 'Design a campaign generation system in Claude Projects with style guides and a human fact-checking step for factual claims.',
      expectedOutcome: 'High-speed creative ideation with strict claim verification.'
    },
    tasks: [
      { id: 'd77-t1', text: 'Review marketing workflow scenarios and Claude Projects best practices', durationMinutes: 20 },
      { id: 'd77-t2', text: 'Complete 4 marketing & communications exam scenarios in simulator', durationMinutes: 30 },
      { id: 'd77-t3', text: 'Document key marketing workflow patterns in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'Marketing copy often makes product claims. Always verify that Claude is not inventing product specs that don\'t exist in the product documentation.',
    examTrapWarning: 'Creative tasks still require hallucination checks! Marketing claims must be grounded in actual product specifications.'
  },
  {
    day: 78,
    month: 3,
    week: 11,
    domainId: 'evaluation',
    title: 'Scenario Drill 4: The Enterprise Compliance Auditor',
    shortSummary: 'Tackle audit and evaluation scenarios: detecting subtle contract discrepancies, verifying executive summaries, and spotting synthetic errors.',
    timeAllocation: { conceptMinutes: 20, handsOnMinutes: 30, reviewMinutes: 10 },
    learningObjectives: [
      'Solve forensic output validation scenario questions',
      'Spot subtle discrepancies between original contracts and AI summaries',
      'Select appropriate verification rubrics for enterprise audits'
    ],
    conceptGuide: 'Audit scenario questions place you in the shoes of a risk officer reviewing AI outputs. You must identify which output is safe to publish and which requires revision.',
    handsOnExercise: {
      taskName: 'Audit Scenario Forensic Drill',
      instructions: 'Review 4 simulated audit reports generated by Claude. Identify the subtle omission or miscalculated ratio that makes the report non-compliant.',
      expectedOutcome: 'Sharp detection of audit discrepancies.'
    },
    tasks: [
      { id: 'd78-t1', text: 'Review forensic audit methodologies and validation heuristics', durationMinutes: 20 },
      { id: 'd78-t2', text: 'Complete 4 audit and verification scenario questions in simulator', durationMinutes: 30 },
      { id: 'd78-t3', text: 'Document audit checklist in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'Check the numbers first! Ratios and percentage comparisons are the most common source of subtle AI synthesis errors.',
    examTrapWarning: 'Never assume that an executive summary captures all material risks; always verify against the underlying report.'
  },
  {
    day: 79,
    month: 3,
    week: 11,
    domainId: 'troubleshooting',
    title: 'Scenario Drill 5: Operational Systems & Troubleshooting',
    shortSummary: 'Debug enterprise failure scenarios: context window overflow, broken JSON schemas, unexpected model refusals, and lazy outputs.',
    timeAllocation: { conceptMinutes: 20, handsOnMinutes: 30, reviewMinutes: 10 },
    learningObjectives: [
      'Diagnose multi-variable operational failures in production pipelines',
      'Select the most cost-effective and reliable fix among 4 proposed solutions',
      'Avoid over-engineering when simple prompt adjustments resolve the issue'
    ],
    conceptGuide: 'Operational troubleshooting questions test your ability to fix broken AI pipelines without unnecessary rework or inflated costs.',
    handsOnExercise: {
      taskName: 'Production Pipeline Debugging Lab',
      instructions: 'A company reports that Claude is truncating customer service transcripts midway through processing. Determine the root cause and select the fix.',
      expectedOutcome: 'Identification of max_tokens limit and implementation of transcript chunking.'
    },
    tasks: [
      { id: 'd79-t1', text: 'Review production pipeline failure modes and fixes', durationMinutes: 20 },
      { id: 'd79-t2', text: 'Complete 4 operational troubleshooting scenario questions', durationMinutes: 30 },
      { id: 'd79-t3', text: 'Log key troubleshooting heuristics in study notes', durationMinutes: 10 }
    ],
    mentorTip: 'The simplest fix that solves the problem without increasing cost or latency is almost always the correct answer on the exam.',
    examTrapWarning: 'Avoid answers that suggest retrying the identical prompt hoping for a different outcome. AI systems require deterministic fixes.'
  },
  {
    day: 80,
    month: 3,
    week: 11,
    domainId: 'models',
    title: 'Multi-Choice Exam Strategy: Pacing & Elimination Tactics',
    shortSummary: 'Master exam mechanics: the 2-minute rule, question stem deconstruction, eliminating distractors, and managing test-day cognitive fatigue.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Master the 2-minute pacing strategy for 60 questions in 120 minutes',
      'Apply the Process of Elimination (POE) to narrow 4 choices to 2 in under 30 seconds',
      'Handle flag-and-return strategy for difficult questions'
    ],
    conceptGuide: 'Passing the CCAO-F exam requires both domain knowledge and test-taking discipline. 60 questions in 120 minutes gives exactly 2 minutes per question. Pacing yourself prevents rushing at the end.',
    handsOnExercise: {
      taskName: 'Speed Elimination Drill',
      instructions: 'Practice the Process of Elimination on 10 practice questions. Cross off 2 obviously wrong distractors within 20 seconds for each.',
      expectedOutcome: 'Dramatic increase in answer speed and confidence.'
    },
    tasks: [
      { id: 'd80-t1', text: 'Study exam pacing and mental stamina preservation strategies', durationMinutes: 25 },
      { id: 'd80-t2', text: 'Execute rapid elimination drill on 10 practice questions', durationMinutes: 25 },
      { id: 'd80-t3', text: 'Set personal time targets for tomorrow full-length mock exam', durationMinutes: 10 }
    ],
    mentorTip: 'Never leave a question unanswered. There is no penalty for guessing on the CCAO-F exam!',
    examTrapWarning: 'Don\'t spend 5 minutes agonizing over a single question. Flag it, make your best guess, and move on.'
  },
  {
    day: 81,
    month: 3,
    week: 11,
    domainId: 'evaluation',
    title: 'Full-Length Mock Exam 1 (60 Questions, 120 Minutes)',
    shortSummary: 'Sit for your first complete 60-question, 120-minute timed simulation of the real CCAO-F exam under strict test conditions.',
    timeAllocation: { conceptMinutes: 5, handsOnMinutes: 50, reviewMinutes: 5 },
    learningObjectives: [
      'Simulate the complete official CCAO-F exam experience (60 questions, 120 min)',
      'Test your pacing against the 2-minute-per-question target',
      'Baseline your overall scaled score against the 720/1000 passing threshold'
    ],
    conceptGuide: 'This is the ultimate test of your preparation so far. Replicate real testing conditions: quiet room, no notes, full screen timer.',
    handsOnExercise: {
      taskName: 'Full Mock Exam 1 Simulation',
      instructions: 'Complete Mock Exam 1 in the Practice Exam Simulator. Strive to finish within the 120-minute time limit.',
      expectedOutcome: 'Complete 60 questions and receive detailed domain breakdown score.'
    },
    tasks: [
      { id: 'd81-t1', text: 'Set up quiet testing environment and review exam ground rules', durationMinutes: 5 },
      { id: 'd81-t2', text: 'Complete 60-question timed mock exam in simulator', durationMinutes: 50 },
      { id: 'd81-t3', text: 'Record raw score, domain scores, and total time elapsed', durationMinutes: 5 }
    ],
    mentorTip: 'Regardless of your score today, this mock provides the exact diagnostic data you need to guarantee a pass on test day.',
    examTrapWarning: 'Do not panic if you score below 720 on Mock 1. You have 9 full days to remediate your specific weak areas.',
    isMilestone: true,
    milestoneTitle: 'Mock Exam 1 Completed (Week 11 Cleared)',
    milestoneReward: 'Badge: Full Mock 1 Ribbon Unlocked'
  },
  {
    day: 82,
    month: 3,
    week: 12,
    domainId: 'troubleshooting',
    title: 'Mock Exam 1 Comprehensive Item-by-Item Review',
    shortSummary: 'Analyze every single question from Mock Exam 1. Dissect both missed questions and lucky guesses to cement core principles.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Conduct an exhaustive review of all 60 questions from Mock Exam 1',
      'Understand why each correct option was chosen by the exam committee',
      'Identify which of the 7 domains contributed the most point losses'
    ],
    conceptGuide: 'The learning happens in the review, not the test. Go through each question slowly. Write out the core lesson for every question you were unsure about.',
    handsOnExercise: {
      taskName: 'Mock 1 Post-Mortem Analysis',
      instructions: 'Create a spreadsheet ranking the 7 domains by score percentage on Mock 1. Identify your lowest two performing domains.',
      expectedOutcome: 'Clear prioritization for the next 3 days of targeted study.'
    },
    tasks: [
      { id: 'd82-t1', text: 'Review detailed rationales for all questions in Mock Exam 1', durationMinutes: 25 },
      { id: 'd82-t2', text: 'Map errors to specific curriculum days for focused review', durationMinutes: 25 },
      { id: 'd82-t3', text: 'Update the Error Journal with remediated concepts', durationMinutes: 10 }
    ],
    mentorTip: 'Pay special attention to questions where you eliminated two options and guessed wrong between the remaining two.',
    examTrapWarning: 'Do not rationalize your mistakes ("I really meant that"). Be brutally honest with yourself so you don\'t repeat the error.'
  },
  {
    day: 83,
    month: 3,
    week: 12,
    domainId: 'evaluation',
    title: 'Targeted Weak Domain Intensive Refresher',
    shortSummary: 'Spend 1 full focused hour reviewing your lowest-scoring domain from Mock Exam 1 with specialized notes and prompt drills.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Execute intensive remediation on your personal weakest domain',
      'Re-read foundational Anthropic documentation for that domain',
      'Complete 15 focused drill questions in that domain'
    ],
    conceptGuide: 'Targeted practice on your weak spots produces the fastest score gains. If Output Evaluation was low, drill hallucination spotting. If Governance was low, review PII and Constitutional AI.',
    handsOnExercise: {
      taskName: 'Weak Domain Deep Drill',
      instructions: 'Complete 15 targeted practice questions exclusively in your lowest-scoring domain.',
      expectedOutcome: 'Score increase of 15%+ in that specific domain.'
    },
    tasks: [
      { id: 'd83-t1', text: 'Review all curriculum days associated with your target weak domain', durationMinutes: 25 },
      { id: 'd83-t2', text: 'Execute targeted domain question drills in simulator', durationMinutes: 25 },
      { id: 'd83-t3', text: 'Confirm mastery of previously confused concepts', durationMinutes: 10 }
    ],
    mentorTip: 'Turning your weakest domain into a strong domain is the single highest-ROI activity in the final two weeks.',
    examTrapWarning: 'Don\'t keep studying the areas you already love and score 90% in. Lean into the discomfort of your weak spots.'
  },
  {
    day: 84,
    month: 3,
    week: 12,
    domainId: 'evaluation',
    title: 'Full-Length Mock Exam 2 (60 Questions, 120 Minutes)',
    shortSummary: 'Sit for Mock Exam 2 to measure score improvement, refine your pacing, and validate weak-domain remediation.',
    timeAllocation: { conceptMinutes: 5, handsOnMinutes: 50, reviewMinutes: 5 },
    learningObjectives: [
      'Take second full-length 60-question mock exam under test conditions',
      'Target a score >= 750 (comfortably above the 720 passing threshold)',
      'Assess pacing improvements and reduction in test anxiety'
    ],
    conceptGuide: 'Mock 2 validates your remediation from Days 82 and 83. You should feel more comfortable with scenario stems and process of elimination.',
    handsOnExercise: {
      taskName: 'Full Mock Exam 2 Simulation',
      instructions: 'Complete Mock Exam 2 in the simulator. Focus on maintaining a steady 2-minute-per-question rhythm.',
      expectedOutcome: 'Score improvement of 30-50 points over Mock 1.'
    },
    tasks: [
      { id: 'd84-t1', text: 'Review pacing targets and enter test mode', durationMinutes: 5 },
      { id: 'd84-t2', text: 'Complete Mock Exam 2 in the practice simulator', durationMinutes: 50 },
      { id: 'd84-t3', text: 'Compare results with Mock 1 and analyze score trajectory', durationMinutes: 5 }
    ],
    mentorTip: 'Notice how much faster you recognize the distractors today. Your intuition is becoming finely tuned.',
    examTrapWarning: 'Don\'t celebrate too early if you score 800+. Stay focused through the final week to lock in your score.'
  },
  {
    day: 85,
    month: 3,
    week: 12,
    domainId: 'troubleshooting',
    title: 'Mock Exam 2 Item Analysis & Misconceptions Log',
    shortSummary: 'Analyze Mock Exam 2 results, log remaining misconceptions, and verify that score gains are consistent across all 7 domains.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Dissect remaining errors from Mock Exam 2',
      'Verify that all 7 domains are now scoring above 70%',
      'Eliminate any lingering edge-case doubts'
    ],
    conceptGuide: 'At this stage, you should only have a few minor misconceptions left. Clean them up now so you enter exam week with total confidence.',
    handsOnExercise: {
      taskName: 'Final Misconceptions Resolution',
      instructions: 'Review any questions missed on Mock 2. Write a 1-sentence rule for each that completely clarifies the correct approach.',
      expectedOutcome: 'Zero unresolved conceptual ambiguities remaining.'
    },
    tasks: [
      { id: 'd85-t1', text: 'Review detailed rationales for Mock Exam 2 missed items', durationMinutes: 25 },
      { id: 'd85-t2', text: 'Write 1-sentence resolution rules in personal study guide', durationMinutes: 25 },
      { id: 'd85-t3', text: 'Verify all 7 domain scores are in passing territory', durationMinutes: 10 }
    ],
    mentorTip: 'You are now consistently scoring in passing territory. The finish line is in sight!',
    examTrapWarning: 'Watch out for fatigue. Maintain your 1-hour daily discipline and don\'t burn out with 5-hour marathon cram sessions.'
  },
  {
    day: 86,
    month: 3,
    week: 12,
    domainId: 'models',
    title: 'The Ultimate CCAO-F Cheat Sheet: Memorization Sprint',
    shortSummary: 'Memorize all key exam constants: model parameters, context window limits, token ratios, domain weightings, and XML conventions.',
    timeAllocation: { conceptMinutes: 25, handsOnMinutes: 25, reviewMinutes: 10 },
    learningObjectives: [
      'Memorize the 7 domain weights (Output Eval 21%, Workflow 16%, Governance 15%, etc.)',
      'Lock in model specifications (200k tokens, Haiku vs Sonnet vs Opus pricing tiers)',
      'Review official XML tag naming conventions (<context>, <instructions>, <example>)'
    ],
    conceptGuide: 'Certain facts should be memorized cold so you don\'t waste a second thinking about them on test day.',
    handsOnExercise: {
      taskName: 'Active Recall Memorization Drill',
      instructions: 'Write out the full CCAO-F Cheat Sheet from memory on a blank sheet of paper: 7 domains, weights, model matrix, and tag rules.',
      expectedOutcome: '100% accurate recall of all core exam constants.'
    },
    tasks: [
      { id: 'd86-t1', text: 'Study the comprehensive CCAO-F Master Cheat Sheet', durationMinutes: 25 },
      { id: 'd86-t2', text: 'Perform blank-page active recall reproduction drill', durationMinutes: 25 },
      { id: 'd86-t3', text: 'Verify accuracy against the Knowledge Vault reference', durationMinutes: 10 }
    ],
    mentorTip: 'Having these numbers at your fingertips gives you instant confidence on the first 10 questions of the exam.',
    examTrapWarning: 'Don\'t confuse Claude 3 Opus specs with Claude 3.5 Sonnet benchmarks. Keep versions distinct in your mind.'
  },
  {
    day: 87,
    month: 3,
    week: 12,
    domainId: 'evaluation',
    title: 'Flashcard Speed Run: 100 Core CCAO-F Concepts',
    shortSummary: 'High-speed rapid-fire drill across 100 core concepts spanning all 7 syllabus domains to lock in lightning-fast recall.',
    timeAllocation: { conceptMinutes: 20, handsOnMinutes: 30, reviewMinutes: 10 },
    learningObjectives: [
      'Review 100 high-yield concepts across all 7 domains in 45 minutes',
      'Achieve sub-10-second instant recall for standard definitions',
      'Build peak cognitive sharpness and confidence'
    ],
    conceptGuide: 'Fast recognition of keywords and concepts allows you to read questions faster and eliminates hesitation between answer choices.',
    handsOnExercise: {
      taskName: '100-Concept Rapid Fire Drill',
      instructions: 'Complete a rapid-fire flashcard run through 100 concepts in the Knowledge Vault. Aim for 95%+ instant recognition.',
      expectedOutcome: 'Effortless, reflexive mastery of all exam terminology.'
    },
    tasks: [
      { id: 'd87-t1', text: 'Execute 100-concept flashcard speed run', durationMinutes: 30 },
      { id: 'd87-t2', text: 'Review the 5 hardest cards with mentor explanations', durationMinutes: 20 },
      { id: 'd87-t3', text: 'Celebrate total conceptual fluency', durationMinutes: 10 }
    ],
    mentorTip: 'Your brain has absorbed 87 days of structured learning. Trust the neural pathways you have built over 87 hours of practice.',
    examTrapWarning: 'Don\'t overthink simple questions on the exam. If an answer seems obviously correct, it probably is!'
  },
  {
    day: 88,
    month: 3,
    week: 12,
    domainId: 'evaluation',
    title: 'Full-Length Mock Exam 3: Final Benchmark Simulation',
    shortSummary: 'Take your final full-length 60-question mock exam. Confirm your mastery, lock in your test-day strategy, and celebrate your readiness.',
    timeAllocation: { conceptMinutes: 5, handsOnMinutes: 50, reviewMinutes: 5 },
    learningObjectives: [
      'Complete final 60-question mock exam under strict proctored simulation',
      'Target a score >= 800/1000 (commanding pass margin)',
      'Finalize your test-day time management plan'
    ],
    conceptGuide: 'This is your final dress rehearsal. Treat it with the exact seriousness and focus of the real exam day.',
    handsOnExercise: {
      taskName: 'Final Dress Rehearsal Simulation',
      instructions: 'Complete Mock Exam 3. Aim to finish with at least 15 minutes to spare for reviewing flagged questions.',
      expectedOutcome: 'High score demonstrating clear readiness for the official certification.'
    },
    tasks: [
      { id: 'd88-t1', text: 'Finalize testing conditions and start 120-minute timer', durationMinutes: 5 },
      { id: 'd88-t2', text: 'Complete Mock Exam 3 in the practice simulator', durationMinutes: 50 },
      { id: 'd88-t3', text: 'Record final benchmark score and celebrate your achievement', durationMinutes: 5 }
    ],
    mentorTip: 'Look at the progress from Day 1 to Day 88. You are ready to pass this exam with flying colors.',
    examTrapWarning: 'Do not study late tonight. Sleep and recovery are your highest priority for peak cognitive performance.',
    isMilestone: true,
    milestoneTitle: 'Mock Exam 3 Mastered (Week 12 Cleared)',
    milestoneReward: 'Badge: Final Mock Trophy Unlocked'
  },
  {
    day: 89,
    month: 3,
    week: 13,
    domainId: 'models',
    title: 'Test-Day Logistics, Proctoring Rules & Exam Protocol',
    shortSummary: 'Prepare your test environment: online proctoring requirements, webcam/ID verification, permitted items, and pacing strategy.',
    timeAllocation: { conceptMinutes: 30, handsOnMinutes: 20, reviewMinutes: 10 },
    learningObjectives: [
      'Understand online proctored exam technical requirements (webcam, microphone, clean desk policy)',
      'Prepare primary government photo ID matching registration name',
      'Review permitted items, scratch paper policies, and room inspection protocols'
    ],
    conceptGuide: 'Technical or proctoring surprises can cause unnecessary stress. Setting up your room, testing your browser, and having your ID ready ensures a smooth test day.',
    handsOnExercise: {
      taskName: 'Test Environment Audit & Checklist',
      instructions: 'Clear your desk completely. Test webcam and mic. Check that your government ID is within arm\'s reach and not expired.',
      expectedOutcome: '100% compliance with proctoring standards.'
    },
    tasks: [
      { id: 'd89-t1', text: 'Read the official Anthropic / exam provider testing guidelines and rules', durationMinutes: 25 },
      { id: 'd89-t2', text: 'Perform physical testing space audit (lighting, desk clearance, power supply)', durationMinutes: 25 },
      { id: 'd89-t3', text: 'Prepare test-day hydration and set alarm for exam check-in time', durationMinutes: 10 }
    ],
    mentorTip: 'Log in 15-20 minutes before your scheduled appointment time to complete the ID check and room scan without rushing.',
    examTrapWarning: 'Ensure no second monitor is plugged in, and remove any smartwatches or headphones from the testing area.'
  },
  {
    day: 90,
    month: 3,
    week: 13,
    domainId: 'evaluation',
    title: 'Day 90 Graduation: Certified Associate Mindset & Pep Talk',
    shortSummary: '90 days complete! 90 hours of dedicated practice logged. Review your full journey, unlock your CCAO-F Champion Trophy, and claim your credential!',
    timeAllocation: { conceptMinutes: 20, handsOnMinutes: 25, reviewMinutes: 15 },
    learningObjectives: [
      'Celebrate completing all 90 days of the CCAO-F study curriculum',
      'Review your cumulative achievements: 90 hours logged, 7 domains mastered',
      'Step into the exam room with the calm confidence of a true domain expert'
    ],
    conceptGuide: 'You have invested 90 hours of intentional, structured practice. You understand models, prompt architecture, project knowledge, business workflows, AI ethics, output evaluation, and troubleshooting better than 99% of practitioners.',
    handsOnExercise: {
      taskName: 'Certification Readiness Self-Certification',
      instructions: 'Review your complete 90-day checklist and progress tracker. Generate and view your CCAO-F Graduation Certificate Preview.',
      expectedOutcome: 'Unwavering confidence and peace of mind on test day.'
    },
    tasks: [
      { id: 'd90-t1', text: 'Review your 90-day progress report and mastery stats', durationMinutes: 20 },
      { id: 'd90-t2', text: 'Read the Mentor Final Pep Talk and visualization guide', durationMinutes: 25 },
      { id: 'd90-t3', text: 'Unlock the CCAO-F Exam Ready Champion Trophy and celebrate!', durationMinutes: 15 }
    ],
    mentorTip: 'Trust your preparation. You have done the work every single day for 3 months. Breathe, read carefully, and enjoy showcasing your expertise!',
    examTrapWarning: 'Remember: passing is 720/1000. You don\'t need 100% to become certified. Stay calm, keep moving, and earn that credential!',
    isMilestone: true,
    milestoneTitle: 'CCAO-F Exam Ready Champion (90 Days Cleared)',
    milestoneReward: 'Trophy: Claude Certified Associate Credential Ready'
  }
];
